[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
EnzymeCore = "f151be2c-9106-41f4-ab19-57ee4f262869"
EnzymeTestUtils = "12d8515a-0907-448a-8884-5fe00fdf1c5a"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PlutoStaticHTML = "359b1769-a58e-495b-9770-312e911026ad"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
Enzyme = {path = ".."}
EnzymeCore = {path = "../lib/EnzymeCore"}
EnzymeTestUtils = {path = "../lib/EnzymeTestUtils"}

[compat]
Documenter = "1"
EnzymeTestUtils = "0.2"
Literate = "2"
